### PR TITLE
Catch interrupted system call

### PR DESCRIPTION
**Pull request by bkanuka**
Patch for Issue #166

### CODE REVIEW

**Comment by DirectXMan12** [comment]
In general, I think this looks good, but please fix the `except` clause.

**Comment by bkanuka** [comment]
What Python version should I be targeting?

**Comment by kanaka** [comment]
Earliest is python 2.4. I keep thinking that we'll be able to get away from this one, but every time we break it we get bug reports so people are still apparently using python 2.4 even today. You should also test it with a python 3.X version (probably python 3.4 if you have it but any python 3.X will probably suffice).

**Comment by DirectXMan12** [comment]
@kanaka : I think, at some point, we should just abandon Python 2.4 support (and probably 2.5), and set a roadmap or policy for deprecating Python versions.

**Comment by kanaka** [comment]
@DirectXMan12 definitely. Maybe we could put a deprecation notice in the code that if you want websockify to continue supporting python2.4 please go vote at this issue. We might get some pulse on how many people are actually still dependent on it. Or maybe refer them to a branch of an older version (although I would hate to get in the business of supporting a bunch of older versions for security, etc).

**Comment by DirectXMan12** [comment]
@kanaka : We're probably coming up on a new release sometime soon (there's a couple things I want to get in first).  I'll add it to the release notes in *big* **bold** ***LETTERS***.  Is that ok?  I'm not aware of any supported platforms that use Python 2.4.  Normally I'm all for deprecation, but I think it's fine in this case just to drop support entirely.

**Comment by kanaka** [comment]
Yes, that's fine.

**Comment by astrand** [comment]
In ThinLinc, our base requirement is Python 2.4 or newer. (See https://www.cendio.com/resources/docs/tag/requirements_server.html). We are using websocket.py.

**Comment by kanaka** [comment]
@astrand so just to be clear, you are wanting to not deprecate python 2.4 compatibility for the time being? Do you have any sense of when that would no longer be needed for your situation?

**Comment by DirectXMan12** [comment]
@astrand : the three "example" Linux platforms listed for ThinLinc all have newer versions of Python.  Python 2.4 hasn't been in most distros for a while (Python 2.4 was in RHEL 5, which is 8 years old at this point, and thus is rapidly nearing EOL).

**Comment by astrand** [comment]
Although we are mainly testing and recommending newer versions such as RHEL7, we still have customers running older versions. That's why our requirements are allowing this. As far as I know, we do not have any decision or information about when we will raise the Python requirement. I believe we still have customers running RHEL 5. For example, see this bug report, which is less than a year old: https://www.cendio.com/bugzilla/show_bug.cgi?id=5180 . So let it put it like this: Is there any real problem with continuing to support Python 2.4? Otherwise, my suggestion is to try to keep supporting that version at least until RHEL5 reaches (non-extended) EOL. According to http://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux, the "End of Production 3 Phase" is 31 March 2017.

**Comment by DirectXMan12** [comment]
@astrand 

> Is there any real problem with continuing to support Python 2.4? 

there's a couple of odd work-arounds that are needed to maintain compatiblity with both Python 2.4 and Python 3.x.  For instance, the exception syntax used in Python 3.x (`except Exception as ex`) was backported to Python 2.6 (which is the version that ships with RHEL 6 and Ubuntu 10.04 LTS).  Otherwise, to capture the actual exception, you have to do something like this: https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L519.

This places a burden on the submitters (they have to know that code has to work with Python 2.4 and Python 3.3+ and test against that), and also somewhat on us (the reviewers).

> I believe we still have customers running RHEL 5. For example, see this bug report, which is less than a year old: https://www.cendio.com/bugzilla/show_bug.cgi?id=5180

Of course.  I'm no stranger to this myself.  However, at a certain point, generally new releases of the project move forward with new versions of Python, and the older versions simply continue to get bugfixes.  Does each version of ThinLinc have a corresponding version of websockify that it ships?  If so, do you have RHEL 5 customers running the latest version of ThinLinc?

We could consider doing a "legacy" branch that just gets appropriate fixes backported, although we don't really get a high number of feature requests against websockify, so I suspect that would be more effort than it's worth.

> Otherwise, my suggestion is to try to keep supporting that version at least until RHEL5 reaches (non-extended) EOL. According to http://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux, the "End of Production 3 Phase" is 31 March 2017.

This isn't a bad plan, although my opinion is that we should drop support sooner ;-)

**Comment by DirectXMan12** [comment]
obsoleted by #175

**Comment by astrand** [comment]
Sorry about the slow response, I'm on paternity leave. Just to follow up on some of the questions:

>"Does each version of ThinLinc have a corresponding version of websockify that it ships? If so, do you have RHEL 5 customers running the latest version of ThinLinc?"

We are shipping a single version of ThinLinc which works on all supported distributions. Yes, I believe we have customers running the latest ThinLinc on RHEL5. 

Creating a branch sounds fine with me as well.

**Pull request closed without merging**
