### PR TITLE
added --target-api option

### PR DESCRIPTION
**Pull request by james-portman**
I have added --target-api option to query tokens against a JSON Rest API

The API URL should be given by the --target-api option,
the token given will be appended to the API URL e.g. for a token of 1234abcd
http://localhost/theapi/ becomes http://localhost/theapi/1234abcd

ip and port of the VNC connection should be returned in JSON format from the API

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Hi!  Thanks  for the contribution.

A couple of commets:

1.  Can you please squash all the of the "cleanup" commits into one or two separate commits?
2. Since this is the second "option" for using tokens, what would be really great would be if we could have a plugin-type system that allowed noVNC to call out to a separate class/method to turn a token into a target pair.  Then, we could simply provide the current functionaly (reading from a file) and your functionality as example/built-in plugins (then you could do something like `--token-plugin websockify.token_loaders.FromFile --token-source file_name_here` or `--token-plugin ValidPythonImportPathHere --token-source "some argument be passed to the class on instantiation"`).

@kanaka : thoughts on number two?

**Comment by james-portman** [comment]
Hi,

Sorry I only realised they weren't squashed afterward but thought it would
still be a good use case for you to see and talk about,

I do think it would be nice to split out the functionality to allow others
in future too yeah,

I will have a look when I get some spare time and do a new, and tidier pull
request

Thanks

**Comment by DirectXMan12** [comment]
For future reference, you can just squash and `git push --force`, and GitHub will update the PR automatically

**Comment by dhilipsiva** [comment]
@james-portman I sent you a pull request. There was a tiny bug in your pull request. Its working now.

**Comment by james-portman** [comment]
Think I have managed to squash it by the way, I did try originally but the push --force made the difference, thanks.

**Comment by dhilipsiva** [comment]
@james-portman Yeah, I just saw you squashed commit. I thought you may not find time and opened PR #158 and I closed after seeing your commit. Thanks for this PR.

**Comment by DirectXMan12** [comment]
Closing in favor of #162.

**Pull request closed without merging**
