### PR TITLE
Implement Ping and Pong heartbeat messages

### PR DESCRIPTION
**Pull request by AricStewart**
Implementations to handle ping and pong heartbeat messages to help with connections through firewalls or proxies and such where regular keep alive traffic would be required.

### CODE REVIEW

**Comment by AricStewart** [comment]
Ok, thanks! Unnecessary pack statement removed.

**Comment by DirectXMan12** [comment]
Besides the nit, LGTM :+1:

**Comment by AricStewart** [comment]
All right.  I have updated to match your recommendation. Thanks for the review.

**Comment by AricStewart** [comment]
Anything further I need to do to allow this to be able to get accepted?

Thanks!
-aric

**Comment by DirectXMan12** [comment]
@AricStewart : hey, sorry, just had something else that really needed to get done.

**Pull request merged**
