### PR TITLE
 Append mime-type while proxy http service using python2

### PR DESCRIPTION
**Pull request by colin-zhou**
https://github.com/novnc/noVNC/issues/1051

With this piece of code, we can make it work under python2 environment

### CODE REVIEW

**Comment by samhed** [comment]
You can force-push to the same branch to overwrite your old commits, that way you won't have to open new PR's.

**Comment by colin-zhou** [comment]
Thanks, I didn't know this until now.

**Comment by CendioOssman** [comment]
We don't really want to start maintaining a list like this, and this should not be necessary on a properly working system. Under what scenario are you seeing problems?

**Comment by colin-zhou** [comment]
I tried to install the mailcap on Ret Hat, but it still not work. From my perspective, the mainstream http server like nginx (its default mime config), apache(its mod_mime config) and uwsgi(read from /etc/mime.type by default) all provide the mime map by itself to make it robust under different environments, so considering map the mime type by the httpserver itself is not bad.  By the way, I will find the rule cause of noVNC not work properly on Red Hat.

**Comment by CendioOssman** [comment]
Works fine with my RHEL 7 machine here:

```
$ python -c 'import mimetypes; mimetypes.init(); print mimetypes.types_map[".svg"];'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '.svg'
$ sudo yum install mailcap
...
$ python -c 'import mimetypes; mimetypes.init(); print mimetypes.types_map[".svg"];'
image/svg+xml
```

**Comment by colin-zhou** [comment]
You are right, a new centos container with mailcap installed works well. Thanks very much.

**Pull request closed without merging**
